### ISSUE TITLE
Dataset selection

### ISSUE THREAD

**Issue by jsleslie** [UBC-MDS/DSCI_522_Group_404#1]
Some ideas of potential datasets

Number of homeless people
https://catalogue.data.gov.bc.ca/dataset/bc-housing-homeless-counts

Cost of housing
https://catalogue.data.gov.bc.ca/dataset/canadian-rental-housing-index

Maybe we can zip these together to see what relationship exists between housing/rental prices and the number of homeless people in Vancouver

**Comment by jsleslie** [comment]
Here's another. We could maybe look at the what's a good predictor of whether a flight will be late

https://www.kaggle.com/usdot/flight-delays#flights.csv

**Comment by lori94** [comment]
finished
