### ISSUE TITLE
Visualizations Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_Group_404#51]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] Great job adding figure numbers and captions! Though your captions could have been a bit more informative, overall this is a very good practice
- - [x] Figure 1:
	- - [x] This isn't a bad plot, but it's a bit hard to see what it's all about.
	- - [x] Definitely switch x and y so categorical axes are on the y-axis and it's easier to read
	- - [ ] *if you have it*, probably more meaningful to plot the full name of the airline rather than the abbreviation 
	- - [x] You [sort](https://github.com/altair-viz/altair/issues/1137#issuecomment-458236850)by the average deaparture delay (either ascending or descending)
- - [x] Figure 2-5:
	- - [x] Adjust Sig figs, too many
	- - [x] Add a more meaningful column name for the index "Unnamed:0" ; ideally for 0 and 1 also, but that's less important
- - [x] I think your tables and figure overall are very reasonable for your project - great work! If you have time and want to be a bit fancy, consider [styling](https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html#Builtin-styles) your tables/dataframes to encode quantitative information

**Comment by jsleslie** [comment]
Thanks for this feedback!

**Comment by jsleslie** [comment]
For Figure 1: The airline names would require us to read in a separate file and to extra wrangling work so I'm putting low down on the priority list - I've done the axis swap and sorted the bars

**Comment by firasm** [comment]
Nice, happy to see you prioritize issues and feature requests !
